# docker-compose.yaml
services:
  jenkins:
    image: ${IMAGE:-jenkins/jenkins:lts}
    privileged: true
    user: root
    ports:
      - 8080:8080
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - renv:/usr/local/lib/R/site-library/renv
      - renv-cache:/root/.cache/R/renv
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_home:
