name: Docker Run
on: [push]

jobs:
    check-docker:
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v4
      - name: down 
        run: docker compose down
      - name: up
        run: docker compose up -d

